name: Python application

on: [pull_request]

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt codecov

      - name: Lint with flake8.
        run: |
          python -m flake8 .

      - name: Automatic test with pytest.
        run: |
          pytest  libpythonpro_exercicio --cov=libpythonpro_exercicio
-name: Coverage
 run: |
   CODECOV_TOKEN="817f56f3-c69f-416a-8678-0cd6d34c96cc"
   codecov
